// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./theme/components/Button.vue')['default']
    HbsButton: typeof import('./theme/components/HbsButton.vue')['default']
  }
}

export { }
